name = "slow-motion"
license = "GPLv2"
licenselink = "https://github.com/vimux/mainroad/blob/master/LICENSE.md"
description = "tbd."
homepage = "https://github.com/SungjaeJung1031/slow-motion/"
demosite = "tbd."
tags = ["blog", "responsive", "light", "multilingual", "customizable", "widgets", "wordpress"]
features = ["blog", "responsive", "multilingual", "widgets", "rss", "disqus", "google analytics", "wordpress"]
min_version = "0.48"

[author]
  name = "Sungjae Jung"
  homepage = "https://github.com/SungjaeJung1031"

# If porting an existing theme
#[original]
#  name = "MH Magazine lite"
#  homepage = "https://wordpress.org/themes/mh-magazine-lite/"
#  repo = "https://themes.trac.wordpress.org/browser/mh-magazine-lite/2.5.6"
